### ISSUE TITLE
Send commands to Neblina from the UART

### ISSUE THREAD

**Issue by acourt** [Motsai/neblina-python#12]
In the streaming menu, you should be able to select what kind of streaming you want or the battery level you need.

**Comment by osarbishei** [comment]
Motion Engine related commands: to stream the 6-axis IMU data, file: _motionenginepackets.md
1- Enable/Disable IMU Stream (Subsystem:0x01, Command: 0x03)

EEPROM related commands: to store/read board IDs, etc., file: _eeprom.md
2- EEPROM_Read (Subsystem: 0x0C, Command: 0x01)
3- EEPROM_Write (Subsystem: 0x0C, Command: 0x02)

NOR flash recorder related commands to store the streaming data, file: _norflash.md
4- FlashEraseAll: to erase the whole flash (Subsystem: 0x0B, Command: 0x01)
5- FlashRecordStartStop: To start or stop recording for a new session (Subsys: 0x0B, Cmd: 0x02)
6- FlashPlayBackStartStop: to start/stop the playback for a pre-recorded session (Subsys: 0x0B, Cmd: 0x03)
