### ISSUE TITLE
Add a test routine command to the main menu for the ProMotion board

### ISSUE THREAD

**Issue by osarbishei** [Motsai/neblina-python#50]
The routine checks the following:
1) Communication with the LSM9DS1 chip, by getting the temperature value
2) Communication between KL26Z and Nordic chips, by getting the firmware versions
3) The EEPROM memory: try a write, followed by a read, which must match the write data
4) Flash Recorder and motion engine's Euler/Quaternion streaming: Do a flash record and playback for both Euler angles and Quaternion data. The number of packets recorded and played back must match.
5) Communication with the power management module: Get battery level (state of charge)

**Comment by acourt** [comment]
It is recommended to use unit test framework and move testing code to separate file like promotionTest.py. Refer to integrationtest.py
