### ISSUE TITLE
The end user of the API should not have to deal with the notion of packets

### ISSUE THREAD

**Issue by acourt** [Motsai/neblina-python#53]
End-user application will use neblinaAPI.py as the API to talk to the module or ProMotion board. The goal of this is to abstract away the notion of packets and UART and deal solely with information important to the user such as quaternions, temperature, flash storage, versions, etc.

**Good:**

``` python
def EEPROMRead(self, readPageNumber):
     (...)
     return packet.data.dataBytes
```

**Bad:**

``` python
def EEPROMRead(self, readPageNumber):
     (...)
     return packet.data
```

`

**Comment by souellet-ms** [comment]
As of 1.0.1, each API function returns a "class" which contains information on the command response. Not a "packet" data but rather a more user friendly interface. Closing this.
