### ISSUE TITLE
Plotting the played back 9-axis MARG raw data, temperature and rotation info

### ISSUE THREAD

**Issue by osarbishei** [Motsai/neblina-python#57]
Plot info:
- 3-axis Accelerometer data
- 3-axis Magnetometer data
- 3-axis Gyroscope data
- Temperature data
- Speed in km/h, where speed in km/h = rpm \* 0.7 \* 3.14 \* 0.06 (rim diameter is 0.7m)

Also display the total distance traveled, i.e., the last Rotation Count multiplied by 3.14*0.7

**Comment by acourt** [comment]
Do the flash sessions create all the same types of packets or will I find packets of different types (mag, imu, etc) in a same flash session when I perform a playback command?

**Comment by osarbishei** [comment]
All packet types are in the same recorded session. Maybe we can append the packets to 4 different lists, while playing back from the session to make it simpler. The packet types are IMU, mag, temperature and rotation.

**Comment by acourt** [comment]
It's not that bad, I'll just go through the session file and put the packets in different lists.

My script so far:

``` python
with open('flashSession1', "rb") as f:
    packetBytes = f.read(20)
    while packetBytes != "":
        packetBytes = f.read(20)
        # Build packet list
        packet = neb.NebResponsePacket(packetBytes)
        subSystem = packet.header.subSystem
        command = packet.header.command
        if subSystem == neb.Subsys_MotionEngine:
            if(command == MotCmd_MAG_Data):
                magPacketList.append(packet)
            elif(command == MotCmd_IMU_Data):
                imuPacketList.append(packet)
        elif subSystem == neb.Subsys_PowerManagement:
            if(command == PowCmd_GetTemperature):
(...)
```

**Comment by osarbishei** [comment]
That works! We just need one more elif for the rotation packet under the motion engine subsystem.

**Comment by acourt** [comment]
oops, forgot rotation. I'm guessing there is going to be a rotation packet every time a rotation is detected?

**Comment by osarbishei** [comment]
Yes. That is correct.

**Comment by acourt** [comment]
![magplot](https://cloud.githubusercontent.com/assets/1243293/13338176/ada23f56-dbed-11e5-9523-fe333c366a08.PNG)

This is data that was uploaded from an earlier recording session. I'm going to add a legend and more details and then tackle the accel and gyro plots. Should I put the rotation packets on the same or separate plot?

**Comment by acourt** [comment]
![accelreadings](https://cloud.githubusercontent.com/assets/1243293/13338702/1cc9e142-dbf1-11e5-9ef9-e443ab943af9.PNG)

Got some accel readings.

**Comment by osarbishei** [comment]
Nice! Looks good. I forgot to say that we would set the accelerometer range to 16g instead of 2g. Can you do that on both boards? It will use the same 16g the next time we power it on and it won't get saturated so easily.

**Comment by osarbishei** [comment]
Just try the command: setAccFullScale 16

**Comment by acourt** [comment]
Ah SHIT, matplotlib doesnt work well on the laptop. fuuuuuu

**Comment by acourt** [comment]
OK, got it to work on the laptop. I'm gonna call it a night an maybe work on it tomorrow on site. I will put the scale to 16g before going to bed.

**Comment by osarbishei** [comment]
Thanks Alex!
